# Generated by Django 5.1.3 on 2025-02-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SampleDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breed_name", models.CharField(max_length=50)),
                (
                    "division_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.division"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="division",
            name="species_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.species"
            ),
        ),
    ]
