# Generated by Django 5.1.3 on 2025-02-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userdetail_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="age",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.userdetail"
            ),
        ),
    ]
