# Generated by Django 5.1.3 on 2025-02-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_animal_breed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="breed",
            old_name="breed_name",
            new_name="animal_name",
        ),
    ]
