# Generated by Django 5.1.3 on 2025-03-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_pet_age_pet_gender_alter_pet_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breed_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.breed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_name",
                    models.CharField(
                        choices=[
                            ("dry food", "dry food"),
                            ("wet food", "wet food"),
                            ("treats", "treats"),
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "breed_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.breed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Health",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breed_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.breed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Toys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breed_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.breed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                (
                    "accessory_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.accessories",
                    ),
                ),
                (
                    "breed_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.breed"
                    ),
                ),
                (
                    "toys_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.toys"
                    ),
                ),
            ],
        ),
    ]
