# Generated by Django 5.1.3 on 2025-02-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_breed_name_breed_animal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="breed",
            name="breed_name",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
