# Generated by Django 5.1.3 on 2025-03-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_accessories_food_health_toys_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="accessory_name",
        ),
        migrations.RemoveField(
            model_name="toys",
            name="breed_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="toys_name",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                choices=[("toys", "toys"), ("accessories", "accessories")],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Accessories",
        ),
        migrations.DeleteModel(
            name="Toys",
        ),
    ]
