# Generated by Django 5.1.3 on 2025-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_product_accessory_name_remove_toys_breed_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="brand_name",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
