# Generated by Django 5.1.3 on 2025-03-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_food_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product",
            field=models.CharField(
                default=None, max_length=50, null=True, verbose_name="Product"
            ),
        ),
    ]
