# Generated by Django 5.1.3 on 2025-03-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_product_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(
                        choices=[
                            ("pharmacy", "pharmacy"),
                            ("supplements", "supplements"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "breed_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.breed"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Health",
        ),
    ]
