# Generated by Django 5.1.3 on 2025-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_medicine_delete_health"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicine",
            old_name="medicine_name",
            new_name="medicine_type",
        ),
        migrations.AddField(
            model_name="food",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("dry food", "dry food"),
                    ("wet food", "wet food"),
                    ("treats", "treats"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="price",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="brand_name",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="medi_name",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="brand_name",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="food_name",
            field=models.CharField(
                default=None, max_length=50, null=True, verbose_name="Food"
            ),
        ),
    ]
