# Generated by Django 5.1.3 on 2025-03-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_rename_medicine_name_medicine_medicine_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="brand_name",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="medicine",
            old_name="brand_name",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="pet",
            old_name="breed_name",
            new_name="breed",
        ),
        migrations.RenameField(
            model_name="pet",
            old_name="division_name",
            new_name="division",
        ),
        migrations.RenameField(
            model_name="pet",
            old_name="pet_name",
            new_name="pet",
        ),
        migrations.RenameField(
            model_name="pet",
            old_name="species_name",
            new_name="species",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="brand_name",
            new_name="brand",
        ),
    ]
