# Generated by Django 5.1.3 on 2025-03-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_brand_name_food_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="price",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
