# Generated by Django 5.1.3 on 2025-03-05 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField()),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pincode", models.IntegerField()),
                ("district", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
                ("landmark", models.CharField(max_length=50)),
                ("door_no", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.userdetail"
                    ),
                ),
            ],
        ),
    ]
